### ISSUE TITLE
Pentaho job creation does not store database name in connection settings

### ISSUE THREAD

**Issue by dibe0014** [SQLPower/power-architect#15]
I tried creating a Kettle job with Architect. Architect did not save the database name in the Kettle connection settings. (Kettle has been renamed to Penaho Data Integration, PDI)

How to reproduce:
* Create new project in Power Architect
* Create source connection
![sourceconnection](https://cloud.githubusercontent.com/assets/16667826/12267258/43630832-b915-11e5-8253-a142ed438b78.PNG)
* Create target connection
![targetconnection](https://cloud.githubusercontent.com/assets/16667826/12267261/4373fb6a-b915-11e5-8144-9a1e0d186bc3.PNG)
* Drag one table from source to playpen
* Verify ETL mapping for one of the columns
![columnsample](https://cloud.githubusercontent.com/assets/16667826/12267257/43620cca-b915-11e5-88e3-5494f23a107a.PNG)
* Go to ETL -> Create Kettle job
* Save Kettle job to file
* Open Kettle transformation in Pentaho Data Integration
* Open the database connections for source and target
* Both connections miss the database name
![sourceconnectionpentaho](https://cloud.githubusercontent.com/assets/16667826/12267259/4368d24e-b915-11e5-85e5-cfe0822a9013.PNG)
![targetconnectionpentaho](https://cloud.githubusercontent.com/assets/16667826/12267260/43700212-b915-11e5-8439-19f651d74bbd.PNG)

**Comment by KirtiMistry** [comment]
This issue occurred  with SQL server Database. Tested with other database (e.g. Postgres) working fine.

**Comment by KirtiMistry** [comment]
Issue resolved. Implemented to display database name (SQL server database) in connection
settings of Pentaho job creation store.

**Comment by dibe0014** [comment]
I can confirm this is working now

**Comment by KirtiMistry** [comment]
This bug reported on bugzilla with bug id # Bug 3169 (http://bugs.sqlpower.ca/bugzilla/post_bug.cgi)

**Comment by vinodgopu** [comment]
Tested in new build it is working as expected
