### ISSUE TITLE
Dead Project ?

### ISSUE THREAD

**Issue by corebreaker** [SQLPower/power-architect#23]
Hello is it a dead project ?

**Comment by KirtiMistry** [comment]
Hi corebreaker,

No its not a dead project. You can find some latest changes. It updated for java 8.

**Comment by corebreaker** [comment]
Hello,

So is there a new released planned ?

**Comment by KirtiMistry** [comment]
Yes, Very soon!

**Comment by corebreaker** [comment]
Good news
