### ISSUE TITLE
Window is too small to choose DB and table and its columns for mapping.

### ISSUE THREAD

**Issue by KirtiMistry** [SQLPower/power-architect#24]
Steps to recreate issue.

1.  create a new Table from  right panel or use existing table from you playpen
2.  add new column.
3.  right click on column > select Column Properties
4. Click on 'source for ETL mapping"
5. This will display drop down, which is populated for data base that you have in your project.

This populated dropdown's with is less. you have to use scroll to select the any column. Its little hard and not user friendly.

Requirements:
width of dropdown needs  to increase.

**Comment by KirtiMistry** [comment]
Changes for the requirement implemented in sqlpower_library at with commit id [fa0ac](https://github.com/SQLPower/sqlpower-library/commit/fa0ac0c25c877ea69de56e95d09c4b7392735a40)

**Comment by vinodgopu** [comment]
Tested in new build bug is fixed
