### ISSUE TITLE
Issue related to export merge join keys to exported kettle job.

### ISSUE THREAD

**Issue by KirtiMistry** [SQLPower/power-architect#26]
Steps to recreate the issue

1) Connect two different database connections (one for source database and second for target database)
2) Drag any 2 tables(tables which are related i.e. have SQLRelationship)from source database connection to playpen.
3) If tables are not related setup  relationship using  button to create a RelationShip from left panel.
4) Create a new table from the button from the left panel.
5) Create columns (as per requirements) (e.g at least 2 or 3 new columns)

![Screen Shot 2020-12-03 at 11 31 01 AM](https://user-images.githubusercontent.com/12957982/101058402-16751500-355b-11eb-9ced-301d83febc31.png)

6) Right click on newly created column  and select **"Column Properties.."** option and click on "source for ETL mapping" button" to map form **source tables** in your playpen.

![Screen Shot 2020-12-03 at 11 32 25 AM](https://user-images.githubusercontent.com/12957982/101058593-4b816780-355b-11eb-9d28-2e90b4407ef9.png)

7) Make sure that the new column must have the same datatype as the mapped column.
8) Click on ETL > Create Kettle Job option in menu.
9) Select Target Database 
10) Select 'Save a job to File' option and specify the path where you want to save the job. and click on OK.

![Screen Shot 2020-12-03 at 11 02 45 AM](https://user-images.githubusercontent.com/12957982/101054659-1d9a2400-3557-11eb-848f-f2047e7f3c8c.png)

This will create the kettle job at specified location.

Go to Pentaho open the job that you just created.

![Screen Shot 2020-12-03 at 11 06 05 AM](https://user-images.githubusercontent.com/12957982/101055059-939e8b00-3557-11eb-8fc5-39cd9798a60e.png)

11) Right click on your output table( e.g std_detail2) click on 'Open Referenced Object' > 'Transformation;  

![Screen Shot 2020-12-03 at 11 08 11 AM](https://user-images.githubusercontent.com/12957982/101055569-0576d480-3558-11eb-8554-a974dc5f8f65.png)

12)  This will open Transformation for your output table (e.g std_detail2). double click on merge join as shown in below image.

![Screen Shot 2020-12-03 at 11 10 29 AM](https://user-images.githubusercontent.com/12957982/101055942-70281000-3558-11eb-87d8-194a5d5ce807.png)

You will see Kets for step1 and 'keys for step2' missing.

![Screen Shot 2020-12-03 at 11 13 39 AM](https://user-images.githubusercontent.com/12957982/101056632-2ee43000-3559-11eb-9f59-b372f5a333e7.png)

The expected behaviour should be:
Keys for 1st step should be the (primary key from your First Step ( e.g Student Table)
Keys for 2nd step should be the (Foreign key from your second Step ( e.g address2Table)

**Expected output should be as below:** 

![Screen Shot 2020-12-03 at 11 35 27 AM](https://user-images.githubusercontent.com/12957982/101059452-4a046f00-355c-11eb-9e0d-e37e33e80e2e.png)

**Comment by vinodgopu** [comment]
Tested in new build, joining key gets populated as expected
