### ISSUE TITLE
Issue in transformation job. Unable to find [JOIN_KEY] field  in a reference stream.

### ISSUE THREAD

**Issue by KirtiMistry** [SQLPower/power-architect#28]
This issue occurred due to not specifying the [JOIN_KEY]  in a Select statement.
Transformation generated from Architect doesn't include a join ket in a Select statement.

**Comment by vinodgopu** [comment]
In select statement joining key is not specified which is std_id

![image](https://user-images.githubusercontent.com/75129278/101383722-7cc5a480-3887-11eb-83bf-0d4b6b88471c.png)

**Comment by vinodgopu** [comment]
Present : in select statement  joining key (i.e. std_id) is not included / specified even though in merge step  joining key has populated,  In pentaho Joining key has to exists in both tables.
![image](https://user-images.githubusercontent.com/75129278/101384384-5fdda100-3888-11eb-861c-33974fee4ddb.png)

**Comment by vinodgopu** [comment]
Expected : 
![image](https://user-images.githubusercontent.com/75129278/101390030-36287800-3890-11eb-9115-70b5f0d7fa78.png)

**Comment by vinodgopu** [comment]
If we don't  have joining key from the input reference stream before joining step Pentaho through error at runtime for example :  
![image](https://user-images.githubusercontent.com/75129278/101503098-bf4ab800-393f-11eb-832a-6b3b3c48f275.png)

**Comment by vinodgopu** [comment]
Tested in new build, working as expected
