### ISSUE TITLE
Add sort before a merge join.

### ISSUE THREAD

**Issue by KirtiMistry** [SQLPower/power-architect#29]
Kettle job generated from Architect when open in Petaho it gives message to add sort before merge join for both tables.
So before merge join sorting of incoming rows is required to produce proper output result, In auto generated kettle transformation sorting is not performed

**Comment by KirtiMistry** [comment]
issue fixed in commit [ee93eaf](https://github.com/SQLPower/power-architect/commit/ee93eaf94dcd370f3e81d0c36470b10e768b78dd)

**Comment by vinodgopu** [comment]
Pentaho merge join step requires sorting of rows before join based on joining key other wise the out put of merge join may not be correct.  Following is warning message in pentaho : 

![image](https://user-images.githubusercontent.com/75129278/101519538-42c0d500-3951-11eb-9a07-519cc6cb9c7d.png)

**Comment by KirtiMistry** [comment]
Updated to add a sort key for SortRow steps. issue #29. Commit for changes can be found at  [0c857ef](https://github.com/SQLPower/power-architect/commit/0c857ef387cd969cbba60a7c7487543f5956009a) .

**Comment by vinodgopu** [comment]
Sort step is populated before merge join step, and sorting key is also populated
