### ISSUE TITLE
In Pentaho transformation generated from Architect in some cases, The initial step(Table input) includes the target table as well

### ISSUE THREAD

**Issue by KirtiMistry** [SQLPower/power-architect#31]
In Pentaho transformation generated from Architect in some cases, The initial step(Table input) includes the target table as well.

**Comment by KirtiMistry** [comment]
Issue fixed in commit [ee93eaf](https://github.com/SQLPower/power-architect/commit/ee93eaf94dcd370f3e81d0c36470b10e768b78dd)

**Comment by KirtiMistry** [comment]
The issue is fixed in commit [ee93eaf](https://github.com/SQLPower/power-architect/commit/ee93eaf94dcd370f3e81d0c36470b10e768b78dd)

**Comment by vinodgopu** [comment]
Tested in new build working as expected
