### ISSUE TITLE
PROBLEM ON DESIGN WITH POSTGRESQL 9.X , dont support data type "text"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SQLPower/power-architect#9]
```
What steps will reproduce the problem?

I have a connection with POSTGRESQL and database with tables, and many tables 
have on data type   = "TEXT"

So if I
 
1. Open design table
2. Sayme Choose a type for xcolumn, but I dont want change data type, because 
postgresql 9.1 support type text.


What is the expected output? What do you see instead?

Open design table with type "TEXT"

What version of the product are you using? On what operating system?
1.06



```

Original issue reported on code.google.com by `fer...@gmail.com` on 15 Aug 2012 at 2:06

**Comment by KirtiMistry** [comment]
Hi!

There is no "Text" data type for JDBC type. The best data type in JDBC type for text/string is CHAR/ VARCHAR/ LONGVARCHAR/ CLOB which can be supported to related Java type. 
check this for more detail info on mapping of JDBC type.
https://db.apache.org/ojb/docu/guides/jdbc-types.html
http://docs.oracle.com/javase/6/docs/technotes/guides/jdbc/getstart/mapping.html#table1

So using 'Power Architect' you can select either LONGVARCHAR or CLOB to support TEXT data type of PostgreSQL.

Hope this will  help you!

-Kirti
